### ISSUE TITLE
Token value needs to be in quotes.

### ISSUE THREAD

**Issue by SauRoNZA** [Concentricc/xiaomi_vacuum#1]
```
vacuum:
  - platform: xiaomi_vacuum
    host: <ip>
    token: "<token>"
```

Making that small change and then it worked fine.
